### ISSUE TITLE
Error - unsupported ramp size 0

### ISSUE THREAD

**Issue by jjwallace** [M1ghtyMushroom/iris#1]
Maybe I am doing this wrong?
![image](https://github.com/M1ghtyMushroom/iris/assets/4450959/c825b13c-d1bf-4623-aa1e-5881fa672734)

Would be cool to play with this:
https://shop.m5stack.com/products/m5stack-dial-esp32-s3-smart-rotary-knob-w-1-28-round-touch-screen

**Comment by M1ghtyMushroom** [comment]
Hi jjwallace,
Thank you for reporting this issue.
I've taken a look into this and found out that the error "unsupported ramp size 0" seems to be related to the xcalib commands in the iris.sh script.
can you please apply the suggested solution in this [reference](https://askubuntu.com/questions/930084/xcalib-error-unsupported-ramp-size) and test it out to see if it resolves the issue on yout end

**Comment by M1ghtyMushroom** [comment]
This issue will be closed in 24 hours if no problems are identified within the script.
